baseURL = 'https://suryakannan.com/'
languageCode = 'en-au'
title = 'Surya Kannan'
buildFuture = true

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

[params]
  defaultTheme = 'light'
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showTableOfContents = true

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

  [params.profileMode]
    enabled = true
    title = "Hi, I'm Surya"
    subtitle = "Welcome to my personal website and blog."
    imageUrl = "/images/profile_pic.jpg"
    imageTitle = "Profile photo"
    imageWidth = 280
    imageHeight = 300

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/SuryaKannan'

  [[params.socialIcons]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/surya-kannan/'

[menu]
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 10

  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 20

  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 30
  
  [[menu.main]]
    name = 'Booklist'
    url = '/booklist/'
    weight = 40

[outputs]
  home = ['HTML', 'RSS', 'JSON']
